name: PR to Discord

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          HOOK: ${{ secrets.DISCORD_HOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"📢 **Pull Request Alert!**\n🔹 **Title:** ${{ github.event.pull_request.title }}\n🔹 **Author:** ${{ github.event.pull_request.user.login }}\n🔹 **Status:** ${{ github.event.action }}\n🔹 **PR Link:** ${{ github.event.pull_request.html_url }}\"}" \
          "$HOOK"

