name: PR to Discord

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"📢 **Pull Request Alert!**\n🔹 **Title:** ${{ github.event.pull_request.title }}\n🔹 **Author:** ${{ github.event.pull_request.user.login }}\n🔹 **Status:** ${{ github.event.action }}\n🔹 **PR Link:** ${{ github.event.pull_request.html_url }}\"}" \
          "https://discord.com/api/webhooks/1337975157716946957/3z26H57orRoCxVZMV9HaCGATK0E4QgvYKjmssZtzqG2YO2pHgp4ZTnlwxlobO01IA795"
